
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-app-demo
  template:
    metadata:
      labels:
        app: vue-app-demo
    spec:
      containers:
      - name: vue-app-demo
        image: gmrn/vue-demo-deployment:latest  # Change to your Docker image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: vue-app-demo-service
spec:
  selector:
    app: vue-app-demo
  ports:
  - nodePort: 31370
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort